default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: rails
  password: rails
  pool: 5

development:
  <<: *default
  database: rails_dev

test:
  <<: *default
  database: rails_test
